### ISSUE TITLE
Universal quantification yields quantification over worlds?

### ISSUE THREAD

**Issue by Weltkaiser** [wo/tpg#32]
TPG proves this formula : `∀x(x=a), Ea |= □Ea`, which seems false because we can find a countermodel:

W = {w0, w1}
D = {0}
a = 0

E : E0 in w0
   ¬E0 in w1

Note that universal quantification ∀ is here understood as a quantification over the domain D. But TPG seems to use the =-elim rule to go from

`¬Ea (v)`
to
`¬Ea (a)`

by using `∀x(x=a) |= v=a`, so quantification over worlds too? Maybe it's not a bug but an intended feature, but it seems weird to me...

On a side note, I always thought that quantification/predication over worlds would be a nice feature (for example if one wants to specify that two worlds cannot share the same propositionnal content). But here, we have a mixed quantification. Something like adding two native predicates D and W to do something like `∀x∀y(Wx ∧ Wy ∧ ¬x=y ⟹ ∃z(Dz ∧ x ⊩ Fz ∧ y ⊩ ¬Fz))`... But of course this would get outside of the classical first-order theory, and would be hard. Especially when we consider that a similar feature already exists via fixed-predicates and dyadic predicates (to demodalize the formulas).

Anyway, have a great day!

**Comment by Weltkaiser** [comment]
Note: my initial aim was to check whether it was possible for two worlds w₀ and w₁ such as Rw₀w₁ to share exactly the same propositional content. The problem is that the only way to do this is to specify the non-reflexivity of R, which is impossible without breaking equality in the propositional content of each world (since modelfinder starts with the smallest models).

For example, I'm looking to see if we have `q |= ¬◇q`. Except that this is obviously not true, since every reflexive model is a counter-model (and is the smallest). So we specify a p to differentiate the worlds and break the reflexivity: `q, p, ¬◇p |= ¬◇q`. But as a result, we no longer have the same propositional content because of p. Ideally, then, we'd like to be able to use R natively in TPG, so as to specify `¬Rww, q |= ¬◇q`, for example. Or I'd just have to fiddle with the modelfinder code to force non-reflexivity, that's an option.

**Comment by wo** [comment]
Thanks! I was half expecting that there would be further problems with the equality reasoner using world variables. I'll have a closer look at this in a few days.

**Comment by wo** [comment]
This is now fixed.

I'm not entirely sure what you were trying to do. If you want to add explicit premises about R then yes, you'll have to translate everything into predicate logic. The modelfinder could easily handle the extra premises, but the prover can't because it's not clear how to integrate them into the existing rules for modal trees.

A model can definitely have multiple worlds with the same "propositional content". I think this was one of the main advantages of Kripke's semantics over Montague's in the 1960s: Montague had construed the worlds as first-order models, so he didn't have modal models in which two worlds satisfy the very same first-order formulas. But I can't on the spot think of a case where this is needed, i.e. of a formula that's only satisfiable in models with such indistinguishable points.

**Comment by Weltkaiser** [comment]
> This is now fixed.
> 
> I'm not entirely sure what you were trying to do. If you want to add explicit premises about R then yes, you'll have to translate everything into predicate logic. The modelfinder could easily handle the extra premises, but the prover can't because it's not clear how to integrate them into the existing rules for modal trees.
> 
> A model can definitely have multiple worlds with the same "propositional content". I think this was one of the main advantages of Kripke's semantics over Montague's in the 1960s: Montague had construed the worlds as first-order models, so he didn't have modal models in which two worlds satisfy the very same first-order formulas. But I can't on the spot think of a case where this is needed, i.e. of a formula that's only satisfiable in models with such indistinguishable points.

Unfortunately, it seems that the problem still exists, in the state in which I described it. We still have `∀x(x=a), Ea |= □Ea`. We also have `∀x(x=a), Ez |= □Ez`!

Thank you for your reply! I've been reading up on Montague semantics, and it's solved a problem I've had for some time :)

**Comment by wo** [comment]
Ah, I forgot to push the change to the server. Done now!
